//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stRepartoRefacciones.wsCoden {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsCoden.wsCodenSoap")]
    public interface wsCodenSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetServerMMResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServerMM", ReplyAction="*")]
        stRepartoRefacciones.wsCoden.GetServerMMResponse GetServerMM(stRepartoRefacciones.wsCoden.GetServerMMRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServerMM", ReplyAction="*")]
        System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.GetServerMMResponse> GetServerMMAsync(stRepartoRefacciones.wsCoden.GetServerMMRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _sDatabse del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredentialsBD", ReplyAction="*")]
        stRepartoRefacciones.wsCoden.GetCredentialsBDResponse GetCredentialsBD(stRepartoRefacciones.wsCoden.GetCredentialsBDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredentialsBD", ReplyAction="*")]
        System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.GetCredentialsBDResponse> GetCredentialsBDAsync(stRepartoRefacciones.wsCoden.GetCredentialsBDRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _sFilial del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveFilial", ReplyAction="*")]
        stRepartoRefacciones.wsCoden.SaveFilialResponse SaveFilial(stRepartoRefacciones.wsCoden.SaveFilialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveFilial", ReplyAction="*")]
        System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.SaveFilialResponse> SaveFilialAsync(stRepartoRefacciones.wsCoden.SaveFilialRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _sSucursal del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveSucursal", ReplyAction="*")]
        stRepartoRefacciones.wsCoden.SaveSucursalResponse SaveSucursal(stRepartoRefacciones.wsCoden.SaveSucursalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveSucursal", ReplyAction="*")]
        System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.SaveSucursalResponse> SaveSucursalAsync(stRepartoRefacciones.wsCoden.SaveSucursalRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _sFactura del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveFacturaMae", ReplyAction="*")]
        stRepartoRefacciones.wsCoden.SaveFacturaMaeResponse SaveFacturaMae(stRepartoRefacciones.wsCoden.SaveFacturaMaeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveFacturaMae", ReplyAction="*")]
        System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.SaveFacturaMaeResponse> SaveFacturaMaeAsync(stRepartoRefacciones.wsCoden.SaveFacturaMaeRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _sFactura del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveFacturaDet", ReplyAction="*")]
        stRepartoRefacciones.wsCoden.SaveFacturaDetResponse SaveFacturaDet(stRepartoRefacciones.wsCoden.SaveFacturaDetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveFacturaDet", ReplyAction="*")]
        System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.SaveFacturaDetResponse> SaveFacturaDetAsync(stRepartoRefacciones.wsCoden.SaveFacturaDetRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _sSucursal del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServerAgencia", ReplyAction="*")]
        stRepartoRefacciones.wsCoden.GetServerAgenciaResponse GetServerAgencia(stRepartoRefacciones.wsCoden.GetServerAgenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServerAgencia", ReplyAction="*")]
        System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.GetServerAgenciaResponse> GetServerAgenciaAsync(stRepartoRefacciones.wsCoden.GetServerAgenciaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServerMMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServerMM", Namespace="http://tempuri.org/", Order=0)]
        public stRepartoRefacciones.wsCoden.GetServerMMRequestBody Body;
        
        public GetServerMMRequest() {
        }
        
        public GetServerMMRequest(stRepartoRefacciones.wsCoden.GetServerMMRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetServerMMRequestBody {
        
        public GetServerMMRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServerMMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServerMMResponse", Namespace="http://tempuri.org/", Order=0)]
        public stRepartoRefacciones.wsCoden.GetServerMMResponseBody Body;
        
        public GetServerMMResponse() {
        }
        
        public GetServerMMResponse(stRepartoRefacciones.wsCoden.GetServerMMResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetServerMMResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetServerMMResult;
        
        public GetServerMMResponseBody() {
        }
        
        public GetServerMMResponseBody(string GetServerMMResult) {
            this.GetServerMMResult = GetServerMMResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCredentialsBDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCredentialsBD", Namespace="http://tempuri.org/", Order=0)]
        public stRepartoRefacciones.wsCoden.GetCredentialsBDRequestBody Body;
        
        public GetCredentialsBDRequest() {
        }
        
        public GetCredentialsBDRequest(stRepartoRefacciones.wsCoden.GetCredentialsBDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCredentialsBDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _sDatabse;
        
        public GetCredentialsBDRequestBody() {
        }
        
        public GetCredentialsBDRequestBody(string _sDatabse) {
            this._sDatabse = _sDatabse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCredentialsBDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCredentialsBDResponse", Namespace="http://tempuri.org/", Order=0)]
        public stRepartoRefacciones.wsCoden.GetCredentialsBDResponseBody Body;
        
        public GetCredentialsBDResponse() {
        }
        
        public GetCredentialsBDResponse(stRepartoRefacciones.wsCoden.GetCredentialsBDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCredentialsBDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public stRepartoRefacciones.wsCoden.ArrayOfString GetCredentialsBDResult;
        
        public GetCredentialsBDResponseBody() {
        }
        
        public GetCredentialsBDResponseBody(stRepartoRefacciones.wsCoden.ArrayOfString GetCredentialsBDResult) {
            this.GetCredentialsBDResult = GetCredentialsBDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveFilialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveFilial", Namespace="http://tempuri.org/", Order=0)]
        public stRepartoRefacciones.wsCoden.SaveFilialRequestBody Body;
        
        public SaveFilialRequest() {
        }
        
        public SaveFilialRequest(stRepartoRefacciones.wsCoden.SaveFilialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveFilialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _sFilial;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _sCveFilial;
        
        public SaveFilialRequestBody() {
        }
        
        public SaveFilialRequestBody(string _sFilial, string _sCveFilial) {
            this._sFilial = _sFilial;
            this._sCveFilial = _sCveFilial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveFilialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveFilialResponse", Namespace="http://tempuri.org/", Order=0)]
        public stRepartoRefacciones.wsCoden.SaveFilialResponseBody Body;
        
        public SaveFilialResponse() {
        }
        
        public SaveFilialResponse(stRepartoRefacciones.wsCoden.SaveFilialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveFilialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SaveFilialResult;
        
        public SaveFilialResponseBody() {
        }
        
        public SaveFilialResponseBody(int SaveFilialResult) {
            this.SaveFilialResult = SaveFilialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveSucursalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveSucursal", Namespace="http://tempuri.org/", Order=0)]
        public stRepartoRefacciones.wsCoden.SaveSucursalRequestBody Body;
        
        public SaveSucursalRequest() {
        }
        
        public SaveSucursalRequest(stRepartoRefacciones.wsCoden.SaveSucursalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveSucursalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _sSucursal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _sCveSucursal;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int _iIdFilial;
        
        public SaveSucursalRequestBody() {
        }
        
        public SaveSucursalRequestBody(string _sSucursal, string _sCveSucursal, int _iIdFilial) {
            this._sSucursal = _sSucursal;
            this._sCveSucursal = _sCveSucursal;
            this._iIdFilial = _iIdFilial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveSucursalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveSucursalResponse", Namespace="http://tempuri.org/", Order=0)]
        public stRepartoRefacciones.wsCoden.SaveSucursalResponseBody Body;
        
        public SaveSucursalResponse() {
        }
        
        public SaveSucursalResponse(stRepartoRefacciones.wsCoden.SaveSucursalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveSucursalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SaveSucursalResult;
        
        public SaveSucursalResponseBody() {
        }
        
        public SaveSucursalResponseBody(int SaveSucursalResult) {
            this.SaveSucursalResult = SaveSucursalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveFacturaMaeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveFacturaMae", Namespace="http://tempuri.org/", Order=0)]
        public stRepartoRefacciones.wsCoden.SaveFacturaMaeRequestBody Body;
        
        public SaveFacturaMaeRequest() {
        }
        
        public SaveFacturaMaeRequest(stRepartoRefacciones.wsCoden.SaveFacturaMaeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveFacturaMaeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _sFactura;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _iConsecutivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string _iMovimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string _dtFecFact;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string _sTransaccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string _sCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string _sCveSucursal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string _sCveFilial;
        
        public SaveFacturaMaeRequestBody() {
        }
        
        public SaveFacturaMaeRequestBody(string _sFactura, string _iConsecutivo, string _iMovimiento, string _dtFecFact, string _sTransaccion, string _sCliente, string _sCveSucursal, string _sCveFilial) {
            this._sFactura = _sFactura;
            this._iConsecutivo = _iConsecutivo;
            this._iMovimiento = _iMovimiento;
            this._dtFecFact = _dtFecFact;
            this._sTransaccion = _sTransaccion;
            this._sCliente = _sCliente;
            this._sCveSucursal = _sCveSucursal;
            this._sCveFilial = _sCveFilial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveFacturaMaeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveFacturaMaeResponse", Namespace="http://tempuri.org/", Order=0)]
        public stRepartoRefacciones.wsCoden.SaveFacturaMaeResponseBody Body;
        
        public SaveFacturaMaeResponse() {
        }
        
        public SaveFacturaMaeResponse(stRepartoRefacciones.wsCoden.SaveFacturaMaeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveFacturaMaeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SaveFacturaMaeResult;
        
        public SaveFacturaMaeResponseBody() {
        }
        
        public SaveFacturaMaeResponseBody(int SaveFacturaMaeResult) {
            this.SaveFacturaMaeResult = SaveFacturaMaeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveFacturaDetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveFacturaDet", Namespace="http://tempuri.org/", Order=0)]
        public stRepartoRefacciones.wsCoden.SaveFacturaDetRequestBody Body;
        
        public SaveFacturaDetRequest() {
        }
        
        public SaveFacturaDetRequest(stRepartoRefacciones.wsCoden.SaveFacturaDetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveFacturaDetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _sFactura;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _sNombreArt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string _sCveArt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string _iMovimientoDet;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int _iIdFactMae;
        
        public SaveFacturaDetRequestBody() {
        }
        
        public SaveFacturaDetRequestBody(string _sFactura, string _sNombreArt, string _sCveArt, string _iMovimientoDet, int _iIdFactMae) {
            this._sFactura = _sFactura;
            this._sNombreArt = _sNombreArt;
            this._sCveArt = _sCveArt;
            this._iMovimientoDet = _iMovimientoDet;
            this._iIdFactMae = _iIdFactMae;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveFacturaDetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveFacturaDetResponse", Namespace="http://tempuri.org/", Order=0)]
        public stRepartoRefacciones.wsCoden.SaveFacturaDetResponseBody Body;
        
        public SaveFacturaDetResponse() {
        }
        
        public SaveFacturaDetResponse(stRepartoRefacciones.wsCoden.SaveFacturaDetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveFacturaDetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SaveFacturaDetResult;
        
        public SaveFacturaDetResponseBody() {
        }
        
        public SaveFacturaDetResponseBody(int SaveFacturaDetResult) {
            this.SaveFacturaDetResult = SaveFacturaDetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServerAgenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServerAgencia", Namespace="http://tempuri.org/", Order=0)]
        public stRepartoRefacciones.wsCoden.GetServerAgenciaRequestBody Body;
        
        public GetServerAgenciaRequest() {
        }
        
        public GetServerAgenciaRequest(stRepartoRefacciones.wsCoden.GetServerAgenciaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetServerAgenciaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _sSucursal;
        
        public GetServerAgenciaRequestBody() {
        }
        
        public GetServerAgenciaRequestBody(string _sSucursal) {
            this._sSucursal = _sSucursal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServerAgenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServerAgenciaResponse", Namespace="http://tempuri.org/", Order=0)]
        public stRepartoRefacciones.wsCoden.GetServerAgenciaResponseBody Body;
        
        public GetServerAgenciaResponse() {
        }
        
        public GetServerAgenciaResponse(stRepartoRefacciones.wsCoden.GetServerAgenciaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetServerAgenciaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public stRepartoRefacciones.wsCoden.ArrayOfString GetServerAgenciaResult;
        
        public GetServerAgenciaResponseBody() {
        }
        
        public GetServerAgenciaResponseBody(stRepartoRefacciones.wsCoden.ArrayOfString GetServerAgenciaResult) {
            this.GetServerAgenciaResult = GetServerAgenciaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsCodenSoapChannel : stRepartoRefacciones.wsCoden.wsCodenSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsCodenSoapClient : System.ServiceModel.ClientBase<stRepartoRefacciones.wsCoden.wsCodenSoap>, stRepartoRefacciones.wsCoden.wsCodenSoap {
        
        public wsCodenSoapClient() {
        }
        
        public wsCodenSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsCodenSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCodenSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCodenSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        stRepartoRefacciones.wsCoden.GetServerMMResponse stRepartoRefacciones.wsCoden.wsCodenSoap.GetServerMM(stRepartoRefacciones.wsCoden.GetServerMMRequest request) {
            return base.Channel.GetServerMM(request);
        }
        
        public string GetServerMM() {
            stRepartoRefacciones.wsCoden.GetServerMMRequest inValue = new stRepartoRefacciones.wsCoden.GetServerMMRequest();
            inValue.Body = new stRepartoRefacciones.wsCoden.GetServerMMRequestBody();
            stRepartoRefacciones.wsCoden.GetServerMMResponse retVal = ((stRepartoRefacciones.wsCoden.wsCodenSoap)(this)).GetServerMM(inValue);
            return retVal.Body.GetServerMMResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.GetServerMMResponse> stRepartoRefacciones.wsCoden.wsCodenSoap.GetServerMMAsync(stRepartoRefacciones.wsCoden.GetServerMMRequest request) {
            return base.Channel.GetServerMMAsync(request);
        }
        
        public System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.GetServerMMResponse> GetServerMMAsync() {
            stRepartoRefacciones.wsCoden.GetServerMMRequest inValue = new stRepartoRefacciones.wsCoden.GetServerMMRequest();
            inValue.Body = new stRepartoRefacciones.wsCoden.GetServerMMRequestBody();
            return ((stRepartoRefacciones.wsCoden.wsCodenSoap)(this)).GetServerMMAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        stRepartoRefacciones.wsCoden.GetCredentialsBDResponse stRepartoRefacciones.wsCoden.wsCodenSoap.GetCredentialsBD(stRepartoRefacciones.wsCoden.GetCredentialsBDRequest request) {
            return base.Channel.GetCredentialsBD(request);
        }
        
        public stRepartoRefacciones.wsCoden.ArrayOfString GetCredentialsBD(string _sDatabse) {
            stRepartoRefacciones.wsCoden.GetCredentialsBDRequest inValue = new stRepartoRefacciones.wsCoden.GetCredentialsBDRequest();
            inValue.Body = new stRepartoRefacciones.wsCoden.GetCredentialsBDRequestBody();
            inValue.Body._sDatabse = _sDatabse;
            stRepartoRefacciones.wsCoden.GetCredentialsBDResponse retVal = ((stRepartoRefacciones.wsCoden.wsCodenSoap)(this)).GetCredentialsBD(inValue);
            return retVal.Body.GetCredentialsBDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.GetCredentialsBDResponse> stRepartoRefacciones.wsCoden.wsCodenSoap.GetCredentialsBDAsync(stRepartoRefacciones.wsCoden.GetCredentialsBDRequest request) {
            return base.Channel.GetCredentialsBDAsync(request);
        }
        
        public System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.GetCredentialsBDResponse> GetCredentialsBDAsync(string _sDatabse) {
            stRepartoRefacciones.wsCoden.GetCredentialsBDRequest inValue = new stRepartoRefacciones.wsCoden.GetCredentialsBDRequest();
            inValue.Body = new stRepartoRefacciones.wsCoden.GetCredentialsBDRequestBody();
            inValue.Body._sDatabse = _sDatabse;
            return ((stRepartoRefacciones.wsCoden.wsCodenSoap)(this)).GetCredentialsBDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        stRepartoRefacciones.wsCoden.SaveFilialResponse stRepartoRefacciones.wsCoden.wsCodenSoap.SaveFilial(stRepartoRefacciones.wsCoden.SaveFilialRequest request) {
            return base.Channel.SaveFilial(request);
        }
        
        public int SaveFilial(string _sFilial, string _sCveFilial) {
            stRepartoRefacciones.wsCoden.SaveFilialRequest inValue = new stRepartoRefacciones.wsCoden.SaveFilialRequest();
            inValue.Body = new stRepartoRefacciones.wsCoden.SaveFilialRequestBody();
            inValue.Body._sFilial = _sFilial;
            inValue.Body._sCveFilial = _sCveFilial;
            stRepartoRefacciones.wsCoden.SaveFilialResponse retVal = ((stRepartoRefacciones.wsCoden.wsCodenSoap)(this)).SaveFilial(inValue);
            return retVal.Body.SaveFilialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.SaveFilialResponse> stRepartoRefacciones.wsCoden.wsCodenSoap.SaveFilialAsync(stRepartoRefacciones.wsCoden.SaveFilialRequest request) {
            return base.Channel.SaveFilialAsync(request);
        }
        
        public System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.SaveFilialResponse> SaveFilialAsync(string _sFilial, string _sCveFilial) {
            stRepartoRefacciones.wsCoden.SaveFilialRequest inValue = new stRepartoRefacciones.wsCoden.SaveFilialRequest();
            inValue.Body = new stRepartoRefacciones.wsCoden.SaveFilialRequestBody();
            inValue.Body._sFilial = _sFilial;
            inValue.Body._sCveFilial = _sCveFilial;
            return ((stRepartoRefacciones.wsCoden.wsCodenSoap)(this)).SaveFilialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        stRepartoRefacciones.wsCoden.SaveSucursalResponse stRepartoRefacciones.wsCoden.wsCodenSoap.SaveSucursal(stRepartoRefacciones.wsCoden.SaveSucursalRequest request) {
            return base.Channel.SaveSucursal(request);
        }
        
        public int SaveSucursal(string _sSucursal, string _sCveSucursal, int _iIdFilial) {
            stRepartoRefacciones.wsCoden.SaveSucursalRequest inValue = new stRepartoRefacciones.wsCoden.SaveSucursalRequest();
            inValue.Body = new stRepartoRefacciones.wsCoden.SaveSucursalRequestBody();
            inValue.Body._sSucursal = _sSucursal;
            inValue.Body._sCveSucursal = _sCveSucursal;
            inValue.Body._iIdFilial = _iIdFilial;
            stRepartoRefacciones.wsCoden.SaveSucursalResponse retVal = ((stRepartoRefacciones.wsCoden.wsCodenSoap)(this)).SaveSucursal(inValue);
            return retVal.Body.SaveSucursalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.SaveSucursalResponse> stRepartoRefacciones.wsCoden.wsCodenSoap.SaveSucursalAsync(stRepartoRefacciones.wsCoden.SaveSucursalRequest request) {
            return base.Channel.SaveSucursalAsync(request);
        }
        
        public System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.SaveSucursalResponse> SaveSucursalAsync(string _sSucursal, string _sCveSucursal, int _iIdFilial) {
            stRepartoRefacciones.wsCoden.SaveSucursalRequest inValue = new stRepartoRefacciones.wsCoden.SaveSucursalRequest();
            inValue.Body = new stRepartoRefacciones.wsCoden.SaveSucursalRequestBody();
            inValue.Body._sSucursal = _sSucursal;
            inValue.Body._sCveSucursal = _sCveSucursal;
            inValue.Body._iIdFilial = _iIdFilial;
            return ((stRepartoRefacciones.wsCoden.wsCodenSoap)(this)).SaveSucursalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        stRepartoRefacciones.wsCoden.SaveFacturaMaeResponse stRepartoRefacciones.wsCoden.wsCodenSoap.SaveFacturaMae(stRepartoRefacciones.wsCoden.SaveFacturaMaeRequest request) {
            return base.Channel.SaveFacturaMae(request);
        }
        
        public int SaveFacturaMae(string _sFactura, string _iConsecutivo, string _iMovimiento, string _dtFecFact, string _sTransaccion, string _sCliente, string _sCveSucursal, string _sCveFilial) {
            stRepartoRefacciones.wsCoden.SaveFacturaMaeRequest inValue = new stRepartoRefacciones.wsCoden.SaveFacturaMaeRequest();
            inValue.Body = new stRepartoRefacciones.wsCoden.SaveFacturaMaeRequestBody();
            inValue.Body._sFactura = _sFactura;
            inValue.Body._iConsecutivo = _iConsecutivo;
            inValue.Body._iMovimiento = _iMovimiento;
            inValue.Body._dtFecFact = _dtFecFact;
            inValue.Body._sTransaccion = _sTransaccion;
            inValue.Body._sCliente = _sCliente;
            inValue.Body._sCveSucursal = _sCveSucursal;
            inValue.Body._sCveFilial = _sCveFilial;
            stRepartoRefacciones.wsCoden.SaveFacturaMaeResponse retVal = ((stRepartoRefacciones.wsCoden.wsCodenSoap)(this)).SaveFacturaMae(inValue);
            return retVal.Body.SaveFacturaMaeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.SaveFacturaMaeResponse> stRepartoRefacciones.wsCoden.wsCodenSoap.SaveFacturaMaeAsync(stRepartoRefacciones.wsCoden.SaveFacturaMaeRequest request) {
            return base.Channel.SaveFacturaMaeAsync(request);
        }
        
        public System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.SaveFacturaMaeResponse> SaveFacturaMaeAsync(string _sFactura, string _iConsecutivo, string _iMovimiento, string _dtFecFact, string _sTransaccion, string _sCliente, string _sCveSucursal, string _sCveFilial) {
            stRepartoRefacciones.wsCoden.SaveFacturaMaeRequest inValue = new stRepartoRefacciones.wsCoden.SaveFacturaMaeRequest();
            inValue.Body = new stRepartoRefacciones.wsCoden.SaveFacturaMaeRequestBody();
            inValue.Body._sFactura = _sFactura;
            inValue.Body._iConsecutivo = _iConsecutivo;
            inValue.Body._iMovimiento = _iMovimiento;
            inValue.Body._dtFecFact = _dtFecFact;
            inValue.Body._sTransaccion = _sTransaccion;
            inValue.Body._sCliente = _sCliente;
            inValue.Body._sCveSucursal = _sCveSucursal;
            inValue.Body._sCveFilial = _sCveFilial;
            return ((stRepartoRefacciones.wsCoden.wsCodenSoap)(this)).SaveFacturaMaeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        stRepartoRefacciones.wsCoden.SaveFacturaDetResponse stRepartoRefacciones.wsCoden.wsCodenSoap.SaveFacturaDet(stRepartoRefacciones.wsCoden.SaveFacturaDetRequest request) {
            return base.Channel.SaveFacturaDet(request);
        }
        
        public int SaveFacturaDet(string _sFactura, string _sNombreArt, string _sCveArt, string _iMovimientoDet, int _iIdFactMae) {
            stRepartoRefacciones.wsCoden.SaveFacturaDetRequest inValue = new stRepartoRefacciones.wsCoden.SaveFacturaDetRequest();
            inValue.Body = new stRepartoRefacciones.wsCoden.SaveFacturaDetRequestBody();
            inValue.Body._sFactura = _sFactura;
            inValue.Body._sNombreArt = _sNombreArt;
            inValue.Body._sCveArt = _sCveArt;
            inValue.Body._iMovimientoDet = _iMovimientoDet;
            inValue.Body._iIdFactMae = _iIdFactMae;
            stRepartoRefacciones.wsCoden.SaveFacturaDetResponse retVal = ((stRepartoRefacciones.wsCoden.wsCodenSoap)(this)).SaveFacturaDet(inValue);
            return retVal.Body.SaveFacturaDetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.SaveFacturaDetResponse> stRepartoRefacciones.wsCoden.wsCodenSoap.SaveFacturaDetAsync(stRepartoRefacciones.wsCoden.SaveFacturaDetRequest request) {
            return base.Channel.SaveFacturaDetAsync(request);
        }
        
        public System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.SaveFacturaDetResponse> SaveFacturaDetAsync(string _sFactura, string _sNombreArt, string _sCveArt, string _iMovimientoDet, int _iIdFactMae) {
            stRepartoRefacciones.wsCoden.SaveFacturaDetRequest inValue = new stRepartoRefacciones.wsCoden.SaveFacturaDetRequest();
            inValue.Body = new stRepartoRefacciones.wsCoden.SaveFacturaDetRequestBody();
            inValue.Body._sFactura = _sFactura;
            inValue.Body._sNombreArt = _sNombreArt;
            inValue.Body._sCveArt = _sCveArt;
            inValue.Body._iMovimientoDet = _iMovimientoDet;
            inValue.Body._iIdFactMae = _iIdFactMae;
            return ((stRepartoRefacciones.wsCoden.wsCodenSoap)(this)).SaveFacturaDetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        stRepartoRefacciones.wsCoden.GetServerAgenciaResponse stRepartoRefacciones.wsCoden.wsCodenSoap.GetServerAgencia(stRepartoRefacciones.wsCoden.GetServerAgenciaRequest request) {
            return base.Channel.GetServerAgencia(request);
        }
        
        public stRepartoRefacciones.wsCoden.ArrayOfString GetServerAgencia(string _sSucursal) {
            stRepartoRefacciones.wsCoden.GetServerAgenciaRequest inValue = new stRepartoRefacciones.wsCoden.GetServerAgenciaRequest();
            inValue.Body = new stRepartoRefacciones.wsCoden.GetServerAgenciaRequestBody();
            inValue.Body._sSucursal = _sSucursal;
            stRepartoRefacciones.wsCoden.GetServerAgenciaResponse retVal = ((stRepartoRefacciones.wsCoden.wsCodenSoap)(this)).GetServerAgencia(inValue);
            return retVal.Body.GetServerAgenciaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.GetServerAgenciaResponse> stRepartoRefacciones.wsCoden.wsCodenSoap.GetServerAgenciaAsync(stRepartoRefacciones.wsCoden.GetServerAgenciaRequest request) {
            return base.Channel.GetServerAgenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<stRepartoRefacciones.wsCoden.GetServerAgenciaResponse> GetServerAgenciaAsync(string _sSucursal) {
            stRepartoRefacciones.wsCoden.GetServerAgenciaRequest inValue = new stRepartoRefacciones.wsCoden.GetServerAgenciaRequest();
            inValue.Body = new stRepartoRefacciones.wsCoden.GetServerAgenciaRequestBody();
            inValue.Body._sSucursal = _sSucursal;
            return ((stRepartoRefacciones.wsCoden.wsCodenSoap)(this)).GetServerAgenciaAsync(inValue);
        }
    }
}
